/**
 * Compiles the hosted form's stylesheet into a module the route handler can
 * inline (#56).
 *
 * `/f` is served by a route handler rather than an App Router page, because the
 * page has no Client Components and no interactivity — it is verified to work
 * with JavaScript blocked — and an App Router route ships react-dom plus the
 * router runtime whether or not a page uses them. That was 134 KB of the 150 KB
 * the form transferred on a customer's paid traffic.
 *
 * A route handler cannot `import "./forms.css"`; nothing processes it. So the
 * same entry the App Router used is compiled here, at build time, and inlined
 * into the document. One request instead of two, and no round trip before the
 * form paints on someone else's page.
 *
 * **The entry is `forms.css` unchanged, not a scoped subset.** Tailwind v4 does
 * not tree-shake per entry, so narrowing the source globs would fork the
 * utility surface for a customer-facing page — a class used only in the form
 * would silently render unstyled. The whole utility set is ~10 KB compiled and
 * that is the right trade.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

import postcss from "postcss";
import tailwind from "@tailwindcss/postcss";
import { transform } from "lightningcss";

const ENTRY = "src/app/(forms)/forms.css";
const OUT = "src/lib/render/form-css.generated.ts";

async function main() {
  const source = await readFile(ENTRY, "utf8");
  const result = await postcss([tailwind()]).process(source, { from: ENTRY, to: OUT });

  // Minified here rather than left to the framework, because nothing downstream
  // of a route handler will do it: the string is inlined into the document
  // exactly as written. lightningcss is already in the tree — Tailwind v4 uses
  // it — so this adds no dependency.
  const { code } = transform({
    filename: "forms.css",
    code: Buffer.from(result.css),
    minify: true,
    // Matches the browsers the rest of the app targets; a form on someone
    // else's page is the last place to drop an older browser.
    targets: { chrome: 111 << 16, firefox: 113 << 16, safari: (16 << 16) | (4 << 8) },
  });
  const css = code.toString();

  await mkdir(path.dirname(OUT), { recursive: true });
  await writeFile(
    OUT,
    "// GENERATED by scripts/build-form-css.mts — do not edit.\n" +
      "// Run `npm run build:form-css`. Regenerated by prebuild and pretest.\n" +
      `export const FORM_CSS = ${JSON.stringify(css)};\n`,
    "utf8",
  );
  console.log(`form css: ${(result.css.length / 1024).toFixed(1)} KB raw -> ${(css.length / 1024).toFixed(1)} KB minified -> ${OUT}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
